language: minimal
dist: xenial

env:
  matrix:
    - PYTHON_VERSION=36
    - PYTHON_VERSION=37

install:
  # Install miniconda
  # -----------------
  - >
    echo "Installing miniconda";
    export CONDA_BASE="https://repo.continuum.io/miniconda/Miniconda";
    wget --quiet ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
    bash miniconda.sh -b -p ${HOME}/miniconda;
    export PATH="${HOME}/miniconda/bin:${PATH}";

  # Configure the test environment
  # ------------------------------
  - >
    echo "Configuring testing environment";
    conda config --set always_yes yes --set changeps1 no;
    conda config --set show_channel_urls True;
    conda config --add channels conda-forge;
    conda update --quiet conda;
    ENV_NAME='iris-grib-dev';
    ENV_FILE='requirements/ci/py${PYTHON_VERSION}.yml';
    cat ${ENV_FILE};
    conda env create --quiet --file=${ENV_FILE};
    source activate ${ENV_NAME};

    # Check installation of eccodes.
    python -m eccodes selfcheck;
    conda install --quiet pip;

  # Download and install iris-test-data
  # -----------------------------------
  - >
    export IRIS_TEST_DATA_REF="https://github.com/SciTools/iris-test-data/archive/master.zip";
    export IRIS_TEST_DATA_LOCATION="${HOME}/iris-test-data";
    mkdir ${IRIS_TEST_DATA_LOCATION};
    wget -O ${IRIS_TEST_DATA_LOCATION}/iris-test-data.zip ${IRIS_TEST_DATA_REF};
    unzip -q ${IRIS_TEST_DATA_LOCATION}/iris-test-data.zip -d ${IRIS_TEST_DATA_LOCATION};

  # Locate iris installation
  # ------------------------
  - export IRIS_DIR=$(python -c "import iris; import os.path; print(os.path.dirname(iris.__file__))")

  # Poke site.cfg to reference iris-test-data
  - >
    SITE_CFG="${IRIS_DIR}/etc/site.cfg";
    echo "[Resources]" > ${SITE_CFG};
    echo "test_data_dir = ${IRIS_TEST_DATA_LOCATION}/iris-test-data-master/test_data" >> ${SITE_CFG};

  # Install iris-grib itself
  # ------------------------
  - pip install . --no-deps

  # Install coveralls for test coverage
  # -----------------------------------
  - pip install coveralls

  # Summarise the environment
  # -------------------------
  - >
    conda list -n ${ENV_NAME};
    conda list -n ${ENV_NAME} --explicit;
    conda info -a;

script:
  # Ensure we can import iris_grib and that the tests pass
  # ------------------------------------------------------
  - coverage run setup.py test

after_success: coveralls
