language: python
sudo: false
env:
  - python=2.7
    iris=master

install:
  # Fetch and install conda
  # -----------------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set show_channel_urls True
  - conda config --add channels scitools
  - conda config --add channels defaults

  # Install iris-grib's dependencies
  # --------------------------------
  - wget https://github.com/scitools/iris/archive/${iris}.tar.gz -O iris.tar.gz;
  - if [ ${iris:0:1} == "v" ]; then
       iris="${iris:1:${#iris}-1}";
    fi
  - tar xzf iris.tar.gz && rm -rf iris.tar.gz && mv iris-${iris} iris_source;
  - conda install --quiet --yes python=${python} --file=./iris_source/minimal-conda-requirements.txt;
  - conda install --quiet --yes ecmwf_grib;
  - pip install ./iris_source --no-deps;
  - rm -rf iris_source;
  - conda list

  # Download iris-test-data
  # --------------------------------
  - export IRIS_TEST_DATA_REF=https://github.com/SciTools/iris-test-data/archive/master.zip
  - export IRIS_TEST_DATA_LOCATION=$HOME/iris-test-data
  - mkdir $IRIS_TEST_DATA_LOCATION
  - wget -O $IRIS_TEST_DATA_LOCATION/iris-test-data.zip ${IRIS_TEST_DATA_REF}
  - unzip -q $IRIS_TEST_DATA_LOCATION/iris-test-data.zip -d $IRIS_TEST_DATA_LOCATION

  # Locate iris installation
  # ------------------------
  - export IRIS_DIR=$(python -c "import iris; import os.path; print os.path.dirname(iris.__file__)")

  # Poke site.cfg to reference iris-test-data
  - SITE_CFG=$IRIS_DIR/etc/site.cfg
  - echo "[Resources]" > $SITE_CFG
  - echo "test_data_dir = ${IRIS_TEST_DATA_LOCATION}/iris-test-data-master/test_data" >> $SITE_CFG

  # Install iris-grib itself
  # ------------------------
  - pip install . --no-deps

  # Install coveralls for test coverage
  # -----------------------------------
  - pip install coveralls

  # Summarise the environment
  # -------------------------
  - conda list

script:
  # Ensure we can import iris_grib and that the tests pass
  # ------------------------------------------------------
  - coverage run setup.py test

after_success: coveralls
